module.exports = {
	POSTGRES_USERNAME: process.env.POSTGRES_USERNAME,
	POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
	POSTGRES_DATABASE_LIST: process.env.POSTGRES_DATABASE_LIST,
	SOCIAL_DB: process.env.SOCIAL_DB,
	SOCIAL_PORT: process.env.SOCIAL_DB,
	MASTER_PORT: process.env.MASTER_PORT,
};
